global:
  scrape_interval: 30s
  evaluation_interval: 1m

scrape_configs:
  - job_name: postgres-exporter
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - "postgres-exporter:9187"

  - job_name: lifecycle
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - "lifecycle:7002"

  - job_name: image-builder
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - "image-builder:7001"

  - job_name: pub
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - "pub:7005"

  - job_name: racetrack-job
    scheme: http
    metrics_path: /metrics
    file_sd_configs:
      - files:
        - '/mnt/plugins/metrics/sd_config_jobs.yaml'
        refresh_interval: 1m
